/* tslint:disable */
/* eslint-disable */
/**
 * dasharr-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RawAxiosRequestConfig } from 'axios';
import globalAxios from '../api/api';

export interface AuthItem {
    'explanation': string;
    'value': string;
}
export interface GetUserStatsQuery {
    'date_from': string;
    'date_to': string;
    /**
     * Comma-separated list of indexer IDs
     */
    'indexer_ids': string;
}
export interface Indexer {
    'auth_data': { [key: string]: AuthItem; };
    'enabled': boolean;
    'error'?: string | null;
    'id': number;
    'name': string;
}
export interface IndexerEnriched {
    'enabled': boolean;
    'error'?: string | null;
    'id': number;
    'last_scraped_at': string;
    'name': string;
}
export interface IndexerStats {
    'indexer_id': number;
    'profile': UserProfileScrapedVec;
    'scraped_at': Array<string>;
}
export interface UpdatedIndexer {
    'auth_data': { [key: string]: AuthItem; };
    'id': number;
}
/**
 *  An analog to ` Vec<UserProfileScraped>  ` with Struct of Array (SoA) layout
 */
export interface UserProfileScrapedVec {
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'avatar': Array<string>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'average_seed_time': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'bonus_points': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'bonus_points_per_hour': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'class': Array<string>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'collages_contrib': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'collages_started': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'donor': Array<boolean | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'downloaded': Array<number>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'downloaded_real': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'groups': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'invited': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'leeching': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'paranoia_text': Array<string | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'posts': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'rank_artists': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'rank_bounty': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'rank_downloaded': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'rank_overall': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'rank_posts': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'rank_requests': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'rank_uploaded': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'rank_uploads': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'ratio': Array<number>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'requests_filled': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'requests_voted': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'required_ratio': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'seed_size': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'seeding': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'snatched': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'torrent_comments': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'uploaded': Array<number>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'uploaded_real': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'uploaded_torrents': Array<number | null>;
    /**
     *  a vector of ` ` from a [`UserProfileScraped`](struct.UserProfileScraped.html)
     */
    'warned': Array<boolean | null>;
}



export const editIndexer = async (updatedIndexer: UpdatedIndexer, options?: RawAxiosRequestConfig): Promise<Indexer> => {
    const response = await globalAxios.request<Indexer>({
        url: '/api/indexers',
        method: 'PUT',
        data: updatedIndexer,
        ...options
    });
    return response.data;
};





export const getIndexers = async (options?: RawAxiosRequestConfig): Promise<Array<Indexer>> => {
    const response = await globalAxios.request<Array<Indexer>>({
        url: '/api/indexers',
        method: 'GET',
        ...options
    });
    return response.data;
};


export const getIndexersAuthData = async (id: number, options?: RawAxiosRequestConfig): Promise<{ [key: string]: AuthItem; }> => {
    const response = await globalAxios.request<{ [key: string]: AuthItem; }>({
        url: `/api/indexers/{id}/auth-data`.replace('{' + 'id' + '}', String(id)),
        method: 'GET',
        ...options
    });
    return response.data;
};




export const getIndexersEnriched = async (onlyWithAvailableData: boolean, options?: RawAxiosRequestConfig): Promise<Array<IndexerEnriched>> => {
    const response = await globalAxios.request<Array<IndexerEnriched>>({
        url: '/api/indexers/enriched',
        method: 'GET',
        params: { 'only_with_available_data': onlyWithAvailableData },
        ...options
    });
    return response.data;
};




export const getIndexersMetricsInPrometheusFormat = async (name: string, options?: RawAxiosRequestConfig): Promise<string> => {
    const response = await globalAxios.request<string>({
        url: `/api/indexers/{name}/prometheus`.replace('{' + 'name' + '}', String(name)),
        method: 'GET',
        ...options
    });
    return response.data;
};




export const toggleIndexer = async (id: number, options?: RawAxiosRequestConfig): Promise<void> => {
    const response = await globalAxios.request<void>({
        url: `/api/indexers/{id}/toggle`.replace('{' + 'id' + '}', String(id)),
        method: 'PUT',
        ...options
    });
    return response.data;
};




export interface GetUserStatsRequest {
    'indexer_ids': string;
    'date_from': string;
    'date_to': string;
}



export const getUserStats = async (request: GetUserStatsRequest, options?: RawAxiosRequestConfig): Promise<Array<IndexerStats>> => {
    const response = await globalAxios.request<Array<IndexerStats>>({
        url: `/api/user-stats`,
        method: 'GET',
        params: { 'indexer_ids': request['indexer_ids'], 'date_from': request['date_from'], 'date_to': request['date_to'] },
        ...options
    });
    return response.data;
};




export const scrapeUserStats = async (options?: RawAxiosRequestConfig): Promise<void> => {
    const response = await globalAxios.request<void>({
        url: '/api/user-stats/scrape',
        method: 'GET',
        ...options
    });
    return response.data;
};

