services:
  db:
    container_name: dasharr_db
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dasharr"]
      interval: 5s
      timeout: 5s
      retries: 5

  dasharr:
    container_name: dasharr
    image: dasharr
    ports:
      - 3000:80
      - 3001:8080
    environment:
      - ENV=Docker
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
